### ISSUE TITLE
Add search bar

### ISSUE THREAD

**Issue by dapplion** [dappnode/DAppNodeDocs#160]
Users consuming the docs would benefit greatly from a search bar for quickly consuming content.

Docusaurus support search bars for free, see https://docusaurus.io/docs/search

**Comment by tropicar** [comment]
In docusaurus we have several options according to the search bar, the options we have are the next ones:
- Algolia: It's a centralised service that offers a searching engine.
- Typesense: It's an open-source searching engine, but you need to build and maintain it.
- Local search: It's a type o searching that uses the navigator. Here you have several projects

It would be a good idea to try some local search, and if this is not enough, we could work on implementing the typesense search engine on our own. I have created this issue https://github.com/easyops-cn/docusaurus-search-local/issues/168 on the repo because it seems there is some errors with the versions. ASAP this error is solved, and the search bar will be implemented.

**Comment by tropicar** [comment]
Related to this task, it was required to update docusaurus core to a newer version. I have updated to the latest stable version of docusaurus. This PR is related to that task https://github.com/dappnode/DAppNodeDocs/pull/174
