### ISSUE TITLE
Split docs from user manual / guide

### ISSUE THREAD

**Issue by Pol-Lanski** [dappnode/DAppNodeDocs#162]
- [ ] ~~Create `guide.dappnode.io`~~
- [ ] ~~Move User guide to new subdomain~~

Edit: New approach being documented below.

**Comment by tropicar** [comment]
We have to make some decisions about this, now we will split the user part and the "docs" part. This new user part, will be done aswell in docusaurus or do we create a webpage? I think this is an important decision. Because if there is a user webpage now, maybe it would be interesting to work more on how the information is presented (in docusaurus we have limitations or we have to implement react code, not only MD how we have done until now). 
I have thought about this because we want to have some elements that can be interesting:
- A easy/beautiful new faqs section, not only a list of questions and answer
- A page that shows packages information, version,required resources, etc. where the user can check information more detailed about everyone.

**Comment by dapplion** [comment]
We shouldn't go to crazy on this, let's go for simpler easy to mantain options
