### ISSUE TITLE
Broken link during the initial setup process

### ISSUE THREAD

**Issue by marsrobertson** [dappnode/DAppNodeDocs#204]
🤷‍♀️ https://dappnode.github.io/DAppNodeDocs/what-can-you-do/

**Comment by alexpeterson91** [comment]
This page hasn't been published yet. We're overhauling the whole documentation since most of it is outdated by years. Been a long and slow process because of the merge taking up all team resources and merge updates and other major previous updates changed processes and requirements entirely necessitating a full rewrite which has been underway for quite a bit now. And is taking a higher priority again now that the mainnet merge is complete. If there's something you'd like to know that you can't find in the docs we can help you out in Discord.
