### ISSUE TITLE
Broken link for resetting DAppNode admin password

### ISSUE THREAD

**Issue by bobsummerwill** [dappnode/DAppNodeDocs#223]
The Reset password page on the device has a dead link.   It points to the following which is no longer there:

https://docs.dappnode.io/user-guide/support/troubleshooting#recover-ui-password

**To Reproduce**

Go to http://my.dappnode and click Forgot Password, then click on ...

If you have lost your recovery token you have to directly access your machine via SSH or by connecting a keyboard and screen and follow this guide

Reset your DAppNode admin password

**Expected behavior**

Go to a working page.

**Screenshots**

**DAppNode version:**

- Package version: 
- OS: 
- Browser 

**Additional context**

**Comment by alexpeterson91** [comment]
The documentation has been rewritten, updated, and republished in a new format since the last software update for the core Dappnode software, it will be updated for the next version to be published in a week. So any links to documentation in the software is definitely outdated since it hasnt had a software update since the documenation was changed.
till then 
https://docs.dappnode.io/user/faq/troubleshooting should help you out!

Thanks for the report! gonna double check this one is updated already for the new release.
