### ISSUE TITLE
Eliminate unused middle steps in path Quickstart > Installation

### ISSUE THREAD

**Issue by Pol-Lanski** [dappnode/DAppNodeDocs#229]
Currently there's a Quickstart > Core > Installation.

<img width="774" alt="Screenshot 2022-12-20 at 10 59 55" src="https://user-images.githubusercontent.com/19168735/208639568-3d55e16a-4661-45ce-b33a-a28aece5cd69.png">

Nevertheless, Core is empty and has no content, and it's not self explanatory; a person needs to click on "core" in order to visualize that they will read installation instructions. 

I suggest eliminating this empty step between in a way that in "Quickstart" there will be "First Steps with Dappnode" and "Installation"

**Comment by alexpeterson91** [comment]
Agreed. Also I don't understand the order of the first docs. The first in order is how to setup your node post install. Then next step is prerequisites and install. Doesn't make sense especially if you're reading the docs entirely and just clicking on the next section at the bottom of each page. Since page one is setup and then page 2 is install it's just backwards.

**Comment by pablomendezroyo** [comment]
documentation refactored
