### ISSUE TITLE
Broken Link "How to connect to your DAppNode VPN" 

### ISSUE THREAD

**Issue by Bravooooh** [dappnode/DAppNodeDocs#233]
On the 
http://my.dappnode/#/vpn/wireguard page, the "How to connect to your DAppNode VPN" link is broken. 

Should forward to https://docs.dappnode.io/user/guides/access/vpn ?

**Comment by alexpeterson91** [comment]
Many links to docs in the UI are or of date. Only some were able to be updated to the newly published documentation which had been live for 2 days before the last core release so we. Only had time to update some links for last core release last week because it was already in the final testing stages when the new docs were published it should all be resolved for the next core release. Thanks for the report though. 👍Sent from my iPhoneOn Dec 28, 2022, at 3:40 AM, Bravooooh ***@***.***> wrote:﻿
On the
http://my.dappnode/#/vpn/wireguard page, the "How to connect to your DAppNode VPN" link is broken.
Should forward to https://docs.dappnode.io/user/guides/access/vpn ?

**Comment by pablomendezroyo** [comment]
documentation refactored
