### ISSUE TITLE
install.dappnode.io link is broken 

### ISSUE THREAD

**Issue by nnnnicholas** [dappnode/DAppNodeDocs#236]
**Describe the bug**
https://install.dappnode.io is broken, resolves to https://docs.dappnode.io/get-started/installation/custom-hardware/installation/overview/

**To Reproduce**

Open https://install.dappnode.io
See 
<img width="788" alt="image" src="https://user-images.githubusercontent.com/1418561/213909095-5b6f4c1c-1425-4b1b-873c-a6e85b5db001.png">

**Comment by alexpeterson91** [comment]
That's not an active link.  Where in the docs are you seeing this link?

**Comment by nnnnicholas** [comment]
I think I landed on dappnode.io rather than dappnode.com via google results. The `Install` button here led me to the page in question.
<img width="1054" alt="image" src="https://user-images.githubusercontent.com/1418561/214061758-6eea6e1c-6e9e-41e0-bf25-eff85a84b00c.png">

**Comment by alexpeterson91** [comment]
this page is offline if you know what led you to our old site, let me know so we can try and update the links.  We had cachig issues on both server and client side that persisted through wipes and when we rebranded and relaunched our store a couplw months ago.  So `https://dappnode.com` is the proper URL for our site, honestly it should have forwarded you to it anyway (we have a dozen or more URLs but they all resolve to `dappnode.com` but again we just had some really strange caching issues that clearing the cache simply didnt do anything on the old `.io` site.

**Comment by nnnnicholas** [comment]
Got it. I just googled dappnode and ended up on the up site. Maybe a dns record update would definitively solve the forwarding issue. Not an expert in that layer.

**Comment by shayanb** [comment]
Same issue on my end as well. 

The dappnode.io home page --> Click on Install --> opens this page that gives me a page not found error `https://docs.dappnode.io/get-started/installation/custom-hardware/installation/overview/`

**Comment by alexpeterson91** [comment]
> Got it. I just googled dappnode and ended up on the old site, which links to a dead page. Maybe a dns record update would definitively solve the forwarding issue.

Thanks for the report we're working on SEO and obviously this is a high priority to resolve. I'm not the webmaster nor have control of the dappnode.io domain but that server was wiped months ago it's some crazy persistent caching. Anyways I've contacted the team members in charge and let them know this is still happening it's really just so bizarre how persistent this caching issue is. Working hard to get this resolved. It's Just weirder now because this was an issue when the new site was first put up and was mostly client side caching issues that just needed a hard reset or browser cache cleared. Now this is persistent on the server side too despite there not even being a server on the other side for months now. I personally don't have a clue what is still delivering any part of that site. But we're working on getting it resolved. M

**Comment by alexpeterson91** [comment]
> Same issue on my end as well. 
> 
> 
> 
> The dappnode.io home page --> Click on Install --> opens this page that gives me a page not found error `https://docs.dappnode.io/get-started/installation/custom-hardware/installation/overview/`

Dappnode.io has been retired as our webpage for months now server doesn't even exist so we can't and won't be updating links. The new webpage+webstore is https://dappnode.com 
I can't even reproduce the error myself because when I try to go to dappnode.io I'm properly redirected to dappnode.com every time. It's possible yiu need to clear your browser cache and flush your DNS to confirm yiur computer doesn't have any old data cached from before the webpage was upgraded and migrated.

**Comment by nnnnicholas** [comment]
Makes sense. `app.dappnode.io` is the 3rd ranked link for "dappnode" google search in a private tab for me.
<img width="871" alt="image" src="https://user-images.githubusercontent.com/1418561/216732296-c46584e3-c6eb-4b3a-8fb8-5d6536d3683b.png">

**Comment by alexpeterson91** [comment]
> Makes sense. `app.dappnode.io` is the 3rd ranked link for "dappnode" google search in a private tab for me.
> 
> <img width="871" alt="image" src="https://user-images.githubusercontent.com/1418561/216732296-c46584e3-c6eb-4b3a-8fb8-5d6536d3683b.png">
> 
> 

`app.dappnode.io` was the web app from which our native NODE token could be staked and provide liquidity to uniswap and sushiswap.  its not our main site nor is it functional at the moment.  interestingly though your screenshot shows the new branding/logo which was rolled out around the same time so google is caching the current data. As it should. SEO takes a while. And we've only been using the .com domain as the main webpage/webstore for a couple months now.

**Comment by nnnnicholas** [comment]
App.dappnode.io loads for me, so it is still being served somewhere. If you have access, perhaps adding a robots.txt to remove it from search indexing will resolve the issue definitively. If you have google search console on the dappnode.io domain you may be able to remove it from indexing without writing a robots.txt file.

**Comment by pablomendezroyo** [comment]
@Marketen could you open an issue at the [installer](https://github.com/dappnode/DAppNode) and [welcome](https://github.com/dappnode/welcome) repositories to review and fix the possible broken documentation links we might have?
